f=open(r'src/components/VoicePlayer.tsx','w',encoding='utf-8')  
f.write('import React, { useState, useEffect, useRef, useCallback } from \" "react\;' + chr(10))  
f.write('import { voiceService } from \../services/voiceService\;' + chr(10))  
f.write('import { VoiceMessageMetadata, DecryptedVoiceMessage } from \../types\;' + chr(10) + chr(10))  
f.write('interface VoicePlayerProps {' + chr(10))  
f.write('  encryptedBlob: Blob;' + chr(10))  
f.write('  metadata: VoiceMessageMetadata;' + chr(10))  
f.write('  privateKeyHex: string;' + chr(10))  
f.write('  isOwn: boolean;' + chr(10))  
f.write('}' + chr(10) + chr(10))  
